from fpdf import FPDF
import tempfile
import os

class AstroReport(FPDF):
    def header(self):
        # Dark Mode Background (#0c0814)
        self.set_fill_color(12, 8, 20)
        self.rect(0, 0, 210, 297, 'F')
        
        # Elegant Gold Title
        self.set_font("helvetica", "B", 22)
        self.set_text_color(212, 175, 55)
        self.cell(0, 15, "ASTRO SUITE: Palmistry Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} - Generated by Astro Suite Engine", align="C")

# Reverted to the original function name so imports don't break!
def generate_premium_pdf(report_text, diagnostic_pil, user_name):
    pdf = AstroReport()
    pdf.add_page()
    
    pdf.set_font("helvetica", "I", 14)
    pdf.set_text_color(200, 200, 200)
    pdf.cell(0, 10, f"Prepared exclusively for: {user_name}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    
    temp_img = tempfile.mktemp(suffix=".jpg")
    diagnostic_pil.save(temp_img, format="JPEG")
    
    pdf.image(temp_img, x=65, y=40, w=80)
    pdf.set_y(150)
    
    pdf.set_font("helvetica", size=11)
    pdf.set_text_color(230, 230, 230)
    
    clean_text = report_text.replace("’", "'").replace("“", '"').replace("”", '"').replace("–", "-").replace("—", "-").replace("*", "")
    pdf.multi_cell(0, 7, clean_text)
    
    if os.path.exists(temp_img): os.remove(temp_img)
    return pdf.output()