"""
shared.ai/palm_knowledge_lookup.py
===================================
Runtime lookup module. Reads palm_knowledge.json (built by knowledge_builder.py)
and returns structured context relevant to this specific palm reading.

No API calls. Runs in milliseconds. Gracefully returns empty if JSON missing.
"""

import json
import re
import os
from functools import lru_cache
from pathlib import Path

# ── PATH TO KNOWLEDGE FILE ─────────────────────────────────────────────────────
# Looks for aiguide/palm_knowledge.json relative to repo root.
# Works on both local machine and Streamlit Cloud.
_HERE = Path(__file__).resolve().parent.parent   # repo root
KNOWLEDGE_PATH = _HERE / "aiguide" / "palm_knowledge.json"


# ── LOADER (cached) ────────────────────────────────────────────────────────────

@lru_cache(maxsize=1)
def _load() -> dict:
    """Load palm_knowledge.json once, cache forever."""
    if not KNOWLEDGE_PATH.exists():
        return {}
    try:
        with open(KNOWLEDGE_PATH, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


# ── MAPPINGS ───────────────────────────────────────────────────────────────────

VITALITY_TO_DOSHA = {
    "pitta": "pitta",
    "vata":  "vata",
    "kapha": "kapha",
}

# Prominent mount → planet name in knowledge JSON
MOUNT_TO_PLANET = {
    "Jupiter":    "jupiter",
    "Saturn":     "saturn",
    "Sun":        "sun",
    "Mercury":    "mercury",
    "Venus":      "venus",
    "Mars_Upper": "mars",
    "Mars_Lower": "mars",
    "Luna":       "moon",
    "Moon":       "moon",
    "Rahu":       "rahu",
    "Ketu":       "ketu",
}

# Hand type → primary planet affinity
HAND_TYPE_TO_PLANET = {
    "Earth Hand": "saturn",
    "Air Hand":   "mercury",
    "Fire Hand":  "sun",
    "Water Hand": "moon",
}

# All 27 nakshatra names (lowercase) for extraction
ALL_NAKSHATRAS = [
    "ashwini", "bharani", "krittika", "rohini", "mrigashira", "ardra",
    "punarvasu", "pushyami", "ashlesha", "magha", "purva phalguni",
    "uttara phalguni", "hasta", "chitra", "swati", "vishakha", "anuradha",
    "jyeshtha", "moola", "purvashadha", "uttarashadha", "shravana",
    "dhanistha", "shatabhisha", "purvabhadra", "uttarabhadra", "revati",
    # alternate spellings
    "purva", "uttara", "dhanishtha", "shatabhishak",
]


# ── HELPERS ───────────────────────────────────────────────────────────────────

def _get_dominant_planet(palm_data: dict, elevations: dict) -> str | None:
    """
    Determine the dominant planet from:
    1. Most elevated mount (highest score)
    2. Hand type
    3. Dominant finger
    """
    k = _load()
    if not k:
        return None

    # 1. Highest mount
    if elevations:
        top_mount = max(elevations, key=lambda m: elevations[m].get("score", 0))
        planet = MOUNT_TO_PLANET.get(top_mount)
        if planet and planet in k.get("planets", {}):
            return planet

    # 2. Hand type
    fd = palm_data.get("finger_data", {})
    ht = fd.get("hand_type", "")
    for ht_key, planet in HAND_TYPE_TO_PLANET.items():
        if ht_key in ht:
            return planet

    return None


def _extract_nakshatra_from_dossier(dossier: str) -> str | None:
    """
    Pull nakshatra name from the dossier text string.
    The dossier is generated by generate_astrology_dossier() and usually
    contains a line like 'Nakshatra: Rohini' or 'Moon Nakshatra: Hasta'.
    """
    if not dossier:
        return None

    text_lower = dossier.lower()

    # Look for explicit nakshatra label
    m = re.search(r'nakshatra[:\s]+([a-z\s]+?)(?:\n|,|\|)', text_lower)
    if m:
        candidate = m.group(1).strip()
        for nk in ALL_NAKSHATRAS:
            if nk in candidate:
                return nk

    # Scan all known names directly
    for nk in sorted(ALL_NAKSHATRAS, key=len, reverse=True):  # longer first to avoid partials
        if nk in text_lower:
            return nk

    return None


def _get_dosha_from_vitality(vitality_str: str) -> str | None:
    """Map vitality reading string to dosha key."""
    vl = vitality_str.lower()
    for dosha, key in VITALITY_TO_DOSHA.items():
        if dosha in vl:
            return key
    return None


def _format_planet_context(planet_data: dict, planet_name: str) -> str:
    """Format planet data into a readable string for the prompt."""
    lines = [f"Planet: {planet_name.title()}"]
    for field in ["general", "health_vitality", "occupations",
                  "hasta_rekha", "alternate_names", "associated_deity",
                  "gemstone", "mantra", "fasting_day"]:
        val = planet_data.get(field)
        if val:
            if isinstance(val, list):
                val = ", ".join(str(v) for v in val if v)
            if val:
                lines.append(f"  {field.replace('_', ' ').title()}: {val}")
    return "\n".join(lines)


def _format_nakshatra_context(nk_data: dict, nk_name: str) -> str:
    """Format nakshatra data into a readable string for the prompt."""
    lines = [f"Nakshatra: {nk_name.title()}"]
    for field in ["rashi_sign", "chinha_symbol", "guna_temperament",
                  "dosha", "devata_deity", "karma_karakas",
                  "shakti", "description", "body_parts", "health_conditions"]:
        val = nk_data.get(field)
        if val:
            if isinstance(val, list):
                val = ", ".join(str(v) for v in val if v)
            if val:
                lines.append(f"  {field.replace('_', ' ').title()}: {val}")
    return "\n".join(lines)


def _format_dosha_context(dosha_data: dict, dosha_name: str) -> str:
    """Format dosha data into a readable string for the prompt."""
    lines = [f"Dosha: {dosha_name.title()}"]
    for field in ["traits", "body_type", "tendencies", "planets"]:
        val = dosha_data.get(field)
        if val:
            if isinstance(val, list):
                val = ", ".join(str(v) for v in val if v)
            if val:
                lines.append(f"  {field.title()}: {val}")
    return "\n".join(lines)


# ── MAIN PUBLIC FUNCTION ───────────────────────────────────────────────────────

def get_palm_context(
    palm_data: dict,
    elevations: dict = None,
    dossier: str = "",
) -> dict:
    """
    Returns structured knowledge context for this palm reading.

    Args:
        palm_data  : the full palm_data dict from analyze_palm_hybrid()
        elevations : mount elevation scores dict (optional)
        dossier    : astrology dossier string (optional, used to find nakshatra)

    Returns dict with keys:
        planet_name     : str  — dominant planet name
        planet_context  : str  — formatted planet data
        nakshatra_name  : str  — nakshatra from dossier
        nakshatra_context: str — formatted nakshatra data
        dosha_name      : str  — dosha from vitality reading
        dosha_context   : str  — formatted dosha data
        formatted_block : str  — ready-to-paste into prompt
        available       : bool — False if palm_knowledge.json is missing
    """
    k = _load()
    result = {
        "planet_name":       None,
        "planet_context":    "",
        "nakshatra_name":    None,
        "nakshatra_context": "",
        "dosha_name":        None,
        "dosha_context":     "",
        "formatted_block":   "",
        "available":         bool(k),
    }

    if not k:
        result["formatted_block"] = "Structured palm knowledge unavailable (palm_knowledge.json not found)."
        return result

    planets    = k.get("planets",    {})
    nakshatras = k.get("nakshatras", {})
    doshas     = k.get("doshas",     {})

    sections = []

    # ── 1. PLANET (from dominant mount / hand type) ───────────────────────────
    planet_name = _get_dominant_planet(palm_data, elevations or {})
    if planet_name and planet_name in planets:
        result["planet_name"]    = planet_name
        result["planet_context"] = _format_planet_context(planets[planet_name], planet_name)
        sections.append(result["planet_context"])

    # ── 2. NAKSHATRA (from dossier) ───────────────────────────────────────────
    nk_name = _extract_nakshatra_from_dossier(dossier)
    if nk_name:
        # Try exact, then partial match
        nk_data = nakshatras.get(nk_name)
        if not nk_data:
            for key in nakshatras:
                if nk_name in key or key in nk_name:
                    nk_data = nakshatras[key]
                    nk_name = key
                    break
        if nk_data:
            result["nakshatra_name"]    = nk_name
            result["nakshatra_context"] = _format_nakshatra_context(nk_data, nk_name)
            sections.append(result["nakshatra_context"])

    # ── 3. DOSHA (from vitality reading) ─────────────────────────────────────
    vitality_str = palm_data.get("vitality_hsv", "")
    dosha_name   = _get_dosha_from_vitality(vitality_str)
    if dosha_name:
        dosha_summary = doshas.get("summary", doshas)
        dosha_data    = dosha_summary.get(dosha_name, {})
        if dosha_data:
            result["dosha_name"]    = dosha_name
            result["dosha_context"] = _format_dosha_context(dosha_data, dosha_name)
            sections.append(result["dosha_context"])

    # ── 4. ASSEMBLE FORMATTED BLOCK ───────────────────────────────────────────
    if sections:
        result["formatted_block"] = "\n\n".join(sections)
    else:
        result["formatted_block"] = "No matching structured knowledge found for detected features."

    return result
